[package]
name = "libtw2-huffman-reference-sys"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
edition = "2021"
rust-version = "1.63.0"

[build-dependencies]
cc = "1.0.3"

[dependencies]
libc = "0.2.0"
