[package]
name = "libtw2-zlib-minimal"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2021"
rust-version = "1.63.0"

[dependencies]
libc = ">=0.1.5,<0.3.0"
libz-sys = ">=0.1.3,<2.0.0"
